# -*- coding: utf-8 -*-
"""
StudyCompanion - 真题库
从 PDF 解析真题，按知识点索引
"""

import json, logging
from typing import Dict, List, Any

logger = logging.getLogger(__name__)

# 历年真题的知识点分类（基于解析PDF提取 + 考纲匹配）
# 格式: year -> [ {q_num, type, topic_ids, keywords} ]
EXAM_INDEX = {
    2025: [
        {"q_num": 1, "type": "选择题", "topic_ids": ["limit_inf_compare"], "keywords": ["无穷小比较", "泰勒"]},
        {"q_num": 2, "type": "选择题", "topic_ids": ["surface_int2"], "keywords": ["曲面积分", "高斯"]},
        {"q_num": 3, "type": "选择题", "topic_ids": ["series_power"], "keywords": ["幂级数", "收敛域"]},
        {"q_num": 4, "type": "选择题", "topic_ids": ["double_int"], "keywords": ["二重积分", "极坐标"]},
        {"q_num": 5, "type": "选择题", "topic_ids": ["eigen_similar"], "keywords": ["特征值", "正交"]},
        {"q_num": 6, "type": "选择题", "topic_ids": ["quadratic_form"], "keywords": ["二次型", "规范形"]},
        {"q_num": 7, "type": "选择题", "topic_ids": ["stat_estimation"], "keywords": ["参数估计"]},
        {"q_num": 8, "type": "选择题", "topic_ids": ["rv_continuous"], "keywords": ["正态分布", "概率"]},
        {"q_num": 9, "type": "选择题", "topic_ids": ["directional_gradient"], "keywords": ["方向导数", "梯度"]},
        {"q_num": 10, "type": "选择题", "topic_ids": ["matrix_rank"], "keywords": ["矩阵秩", "线性方程组"]},
        {"q_num": 11, "type": "填空题", "topic_ids": ["total_diff"], "keywords": ["全微分"]},
        {"q_num": 12, "type": "填空题", "topic_ids": ["ode_linear_high"], "keywords": ["微分方程", "特解"]},
        {"q_num": 13, "type": "填空题", "topic_ids": ["surface_int2"], "keywords": ["曲面积分"]},
        {"q_num": 14, "type": "填空题", "topic_ids": ["defint_compute"], "keywords": ["定积分"]},
        {"q_num": 15, "type": "填空题", "topic_ids": ["det_compute"], "keywords": ["行列式"]},
        {"q_num": 16, "type": "填空题", "topic_ids": ["expectation"], "keywords": ["期望", "方差"]},
        {"q_num": 17, "type": "解答题", "topic_ids": ["limit_seq_criteria"], "keywords": ["数列极限", "夹逼"]},
        {"q_num": 18, "type": "解答题", "topic_ids": ["line_int2"], "keywords": ["曲线积分", "格林"]},
        {"q_num": 19, "type": "解答题", "topic_ids": ["multi_extrema"], "keywords": ["拉格朗日乘数"]},
        {"q_num": 20, "type": "解答题", "topic_ids": ["triple_int"], "keywords": ["三重积分", "球坐标"]},
        {"q_num": 21, "type": "解答题", "topic_ids": ["eigen_similar"], "keywords": ["正交对角化"]},
        {"q_num": 22, "type": "解答题", "topic_ids": ["stat_estimation"], "keywords": ["最大似然", "矩估计"]},
    ],
    2024: [
        {"q_num": 1, "type": "选择题", "topic_ids": ["func_def"], "keywords": ["奇偶函数"]},
        {"q_num": 2, "type": "选择题", "topic_ids": ["limit_ops"], "keywords": ["极限运算"]},
        {"q_num": 3, "type": "选择题", "topic_ids": ["series_power"], "keywords": ["幂级数", "收敛域"]},
        {"q_num": 4, "type": "选择题", "topic_ids": ["derivative_def"], "keywords": ["导数定义"]},
        {"q_num": 5, "type": "选择题", "topic_ids": ["surface_int2"], "keywords": ["曲面积分", "高斯"]},
        {"q_num": 6, "type": "选择题", "topic_ids": ["linear_system"], "keywords": ["向量组", "线性相关"]},
        {"q_num": 7, "type": "选择题", "topic_ids": ["eigen_basic"], "keywords": ["特征值", "秩"]},
        {"q_num": 8, "type": "选择题", "topic_ids": ["quadratic_form"], "keywords": ["二次型", "规范形"]},
        {"q_num": 9, "type": "选择题", "topic_ids": ["rv_continuous"], "keywords": ["正态分布", "概率"]},
        {"q_num": 10, "type": "选择题", "topic_ids": ["stat_estimation"], "keywords": ["参数估计"]},
        {"q_num": 11, "type": "填空题", "topic_ids": ["defint_compute"], "keywords": ["定积分", "奇偶性"]},
        {"q_num": 12, "type": "填空题", "topic_ids": ["ode_linear_high"], "keywords": ["微分方程", "通解"]},
        {"q_num": 13, "type": "填空题", "topic_ids": ["multi_chain"], "keywords": ["偏导数"]},
        {"q_num": 14, "type": "填空题", "topic_ids": ["surface_int2"], "keywords": ["曲面积分", "高斯"]},
        {"q_num": 15, "type": "填空题", "topic_ids": ["series_fourier"], "keywords": ["傅里叶级数"]},
        {"q_num": 16, "type": "填空题", "topic_ids": ["eigen_similar"], "keywords": ["特征值", "迹"]},
        {"q_num": 17, "type": "解答题", "topic_ids": ["limit_seq_criteria"], "keywords": ["数列极限", "夹逼"]},
        {"q_num": 18, "type": "解答题", "topic_ids": ["line_int2"], "keywords": ["曲线积分", "格林"]},
        {"q_num": 19, "type": "解答题", "topic_ids": ["multi_extrema"], "keywords": ["条件极值", "拉格朗日"]},
        {"q_num": 20, "type": "解答题", "topic_ids": ["triple_int"], "keywords": ["三重积分", "球坐标"]},
        {"q_num": 21, "type": "解答题", "topic_ids": ["clt"], "keywords": ["中心极限定理"]},
        {"q_num": 22, "type": "解答题", "topic_ids": ["stat_test"], "keywords": ["假设检验", "t检验"]},
    ],
    2023: [
        {"q_num": 1, "type": "选择题", "topic_ids": ["limit_seq_criteria"], "keywords": ["数列极限", "夹逼"]},
        {"q_num": 2, "type": "选择题", "topic_ids": ["double_int"], "keywords": ["二重积分", "交换次序"]},
        {"q_num": 3, "type": "选择题", "topic_ids": ["series_power"], "keywords": ["幂级数", "和函数"]},
        {"q_num": 4, "type": "选择题", "topic_ids": ["mvt_rolle"], "keywords": ["罗尔定理", "中值定理"]},
        {"q_num": 5, "type": "选择题", "topic_ids": ["line_int2"], "keywords": ["曲线积分", "路径无关"]},
        {"q_num": 6, "type": "选择题", "topic_ids": ["surface_int2"], "keywords": ["曲面积分", "高斯"]},
        {"q_num": 7, "type": "选择题", "topic_ids": ["matrix_rank"], "keywords": ["秩", "方程组"]},
        {"q_num": 8, "type": "选择题", "topic_ids": ["eigen_similar"], "keywords": ["相似对角化"]},
        {"q_num": 9, "type": "选择题", "topic_ids": ["quadratic_definite"], "keywords": ["正定矩阵"]},
        {"q_num": 10, "type": "选择题", "topic_ids": ["independence"], "keywords": ["独立性", "概率"]},
        {"q_num": 11, "type": "填空题", "topic_ids": ["defint_compute"], "keywords": ["定积分", "换元"]},
        {"q_num": 12, "type": "填空题", "topic_ids": ["ode_linear_high"], "keywords": ["微分方程", "特解"]},
        {"q_num": 13, "type": "填空题", "topic_ids": ["multi_chain"], "keywords": ["偏导数", "全微分"]},
        {"q_num": 14, "type": "填空题", "topic_ids": ["double_int"], "keywords": ["二重积分", "交换次序"]},
        {"q_num": 15, "type": "填空题", "topic_ids": ["series_const"], "keywords": ["级数敛散", "p级数"]},
        {"q_num": 16, "type": "填空题", "topic_ids": ["det_compute"], "keywords": ["行列式"]},
        {"q_num": 17, "type": "解答题", "topic_ids": ["multi_extrema"], "keywords": ["条件极值", "拉格朗日"]},
        {"q_num": 18, "type": "解答题", "topic_ids": ["line_int1"], "keywords": ["曲线积分", "弧长"]},
        {"q_num": 19, "type": "解答题", "topic_ids": ["triple_int"], "keywords": ["三重积分", "柱坐标"]},
        {"q_num": 20, "type": "解答题", "topic_ids": ["lln"], "keywords": ["大数定律", "切比雪夫"]},
        {"q_num": 21, "type": "解答题", "topic_ids": ["stat_estimation"], "keywords": ["矩估计", "最大似然"]},
        {"q_num": 22, "type": "解答题", "topic_ids": ["stat_test"], "keywords": ["假设检验"]},
    ],
    2022: [
        {"q_num": 1, "type": "选择题", "topic_ids": ["lhopital"], "keywords": ["洛必达法则"]},
        {"q_num": 2, "type": "选择题", "topic_ids": ["derivative_app_monotonicity"], "keywords": ["单调性", "极值"]},
        {"q_num": 3, "type": "选择题", "topic_ids": ["limit_seq_criteria"], "keywords": ["数列极限", "单调有界"]},
        {"q_num": 4, "type": "选择题", "topic_ids": ["improper"], "keywords": ["反常积分", "敛散性"]},
        {"q_num": 5, "type": "选择题", "topic_ids": ["double_int"], "keywords": ["二重积分", "极坐标"]},
        {"q_num": 6, "type": "选择题", "topic_ids": ["ode_linear_high"], "keywords": ["微分方程", "特解形式"]},
        {"q_num": 7, "type": "选择题", "topic_ids": ["matrix_ops"], "keywords": ["矩阵运算", "逆矩阵"]},
        {"q_num": 8, "type": "选择题", "topic_ids": ["vector_group"], "keywords": ["线性相关", "线性无关"]},
        {"q_num": 9, "type": "选择题", "topic_ids": ["quadratic_form"], "keywords": ["二次型", "配方法"]},
        {"q_num": 10, "type": "选择题", "topic_ids": ["prob_classical"], "keywords": ["古典概型"]},
        {"q_num": 11, "type": "填空题", "topic_ids": ["surface_int2"], "keywords": ["曲面积分"]},
        {"q_num": 12, "type": "填空题", "topic_ids": ["series_power"], "keywords": ["幂级数", "收敛半径"]},
        {"q_num": 13, "type": "填空题", "topic_ids": ["multi_int_app"], "keywords": ["曲面面积"]},
        {"q_num": 14, "type": "填空题", "topic_ids": ["eigen_basic"], "keywords": ["特征值", "行列式"]},
        {"q_num": 15, "type": "填空题", "topic_ids": ["cov_corr"], "keywords": ["协方差", "相关系数"]},
        {"q_num": 16, "type": "填空题", "topic_ids": ["prob_cond"], "keywords": ["条件概率", "贝叶斯"]},
        {"q_num": 17, "type": "解答题", "topic_ids": ["taylor"], "keywords": ["泰勒公式", "极限"]},
        {"q_num": 18, "type": "解答题", "topic_ids": ["line_int2"], "keywords": ["第二类曲线积分", "格林"]},
        {"q_num": 19, "type": "解答题", "topic_ids": ["multi_extrema"], "keywords": ["拉格朗日乘数法"]},
        {"q_num": 20, "type": "解答题", "topic_ids": ["eigen_similar"], "keywords": ["正交对角化"]},
        {"q_num": 21, "type": "解答题", "topic_ids": ["rv_function"], "keywords": ["随机变量函数分布"]},
        {"q_num": 22, "type": "解答题", "topic_ids": ["stat_estimation"], "keywords": ["最大似然估计"]},
    ],
    2021: [
        {"q_num": 1, "type": "选择题", "topic_ids": ["continuity"], "keywords": ["连续性", "可导"]},
        {"q_num": 2, "type": "选择题", "topic_ids": ["multi_chain"], "keywords": ["偏导数", "复合函数"]},
        {"q_num": 3, "type": "选择题", "topic_ids": ["series_power"], "keywords": ["幂级数", "和函数"]},
        {"q_num": 4, "type": "选择题", "topic_ids": ["defint_compute"], "keywords": ["定积分", "比较"]},
        {"q_num": 5, "type": "选择题", "topic_ids": ["quadratic_form"], "keywords": ["二次型", "正交变换"]},
        {"q_num": 6, "type": "选择题", "topic_ids": ["eigen_similar"], "keywords": ["施密特正交化"]},
        {"q_num": 7, "type": "选择题", "topic_ids": ["matrix_block"], "keywords": ["分块矩阵", "秩"]},
        {"q_num": 8, "type": "选择题", "topic_ids": ["independence"], "keywords": ["事件独立性"]},
        {"q_num": 9, "type": "选择题", "topic_ids": ["cov_corr"], "keywords": ["协方差", "方差"]},
        {"q_num": 10, "type": "选择题", "topic_ids": ["stat_estimation"], "keywords": ["最大似然估计"]},
        {"q_num": 11, "type": "填空题", "topic_ids": ["taylor"], "keywords": ["泰勒公式", "极限"]},
        {"q_num": 12, "type": "填空题", "topic_ids": ["ode_linear_high"], "keywords": ["欧拉方程"]},
        {"q_num": 13, "type": "填空题", "topic_ids": ["surface_int2"], "keywords": ["高斯公式"]},
        {"q_num": 14, "type": "填空题", "topic_ids": ["det_compute"], "keywords": ["行列式", "代数余子式"]},
        {"q_num": 15, "type": "填空题", "topic_ids": ["rv_discrete"], "keywords": ["离散分布"]},
        {"q_num": 16, "type": "填空题", "topic_ids": ["prob_classical"], "keywords": ["古典概型"]},
        {"q_num": 17, "type": "解答题", "topic_ids": ["limit_seq_criteria"], "keywords": ["数列极限", "单调有界"]},
        {"q_num": 18, "type": "解答题", "topic_ids": ["surface_int2"], "keywords": ["曲面积分", "斯托克斯"]},
        {"q_num": 19, "type": "解答题", "topic_ids": ["series_power"], "keywords": ["幂级数", "收敛域"]},
        {"q_num": 20, "type": "解答题", "topic_ids": ["linear_system"], "keywords": ["线性方程组", "解结构"]},
        {"q_num": 21, "type": "解答题", "topic_ids": ["eigen_similar"], "keywords": ["正交对角化"]},
        {"q_num": 22, "type": "解答题", "topic_ids": ["rv_function"], "keywords": ["二维正态", "条件分布"]},
    ],
    2020: [
        {"q_num": 1, "type": "选择题", "topic_ids": ["limit_inf_compare"], "keywords": ["无穷小比较"]},
        {"q_num": 2, "type": "选择题", "topic_ids": ["derivative_def"], "keywords": ["可导", "连续"]},
        {"q_num": 3, "type": "选择题", "topic_ids": ["total_diff"], "keywords": ["全微分", "可微"]},
        {"q_num": 4, "type": "选择题", "topic_ids": ["series_power"], "keywords": ["幂级数", "收敛半径"]},
        {"q_num": 5, "type": "选择题", "topic_ids": ["elementary"], "keywords": ["初等变换", "矩阵等价"]},
        {"q_num": 6, "type": "选择题", "topic_ids": ["line_3d"], "keywords": ["空间直线", "共面"]},
        {"q_num": 7, "type": "选择题", "topic_ids": ["prob_cond"], "keywords": ["概率运算", "独立"]},
        {"q_num": 8, "type": "选择题", "topic_ids": ["rv_continuous"], "keywords": ["正态分布"]},
        {"q_num": 9, "type": "填空题", "topic_ids": ["lhopital"], "keywords": ["洛必达", "极限"]},
        {"q_num": 10, "type": "填空题", "topic_ids": ["ode_reducible"], "keywords": ["微分方程", "参数方程"]},
        {"q_num": 11, "type": "填空题", "topic_ids": ["ode_linear_high"], "keywords": ["常系数齐次", "特征方程"]},
        {"q_num": 12, "type": "填空题", "topic_ids": ["partial_deriv"], "keywords": ["偏导数", "变限积分"]},
        {"q_num": 13, "type": "填空题", "topic_ids": ["det_compute"], "keywords": ["行列式", "代数余子式"]},
        {"q_num": 14, "type": "填空题", "topic_ids": ["rv_function"], "keywords": ["随机变量函数"]},
        {"q_num": 15, "type": "解答题", "topic_ids": ["multi_extrema"], "keywords": ["极值", "隐函数"]},
        {"q_num": 16, "type": "解答题", "topic_ids": ["line_int2"], "keywords": ["曲线积分", "格林"]},
        {"q_num": 17, "type": "解答题", "topic_ids": ["series_power"], "keywords": ["幂级数", "和函数"]},
        {"q_num": 18, "type": "解答题", "topic_ids": ["surface_int2"], "keywords": ["曲面积分", "高斯"]},
        {"q_num": 19, "type": "解答题", "topic_ids": ["eigen_similar"], "keywords": ["正交对角化"]},
        {"q_num": 20, "type": "解答题", "topic_ids": ["multi_rv_func"], "keywords": ["二维随机变量"]},
        {"q_num": 21, "type": "解答题", "topic_ids": ["stat_estimation"], "keywords": ["矩估计", "最大似然"]},
        {"q_num": 22, "type": "解答题", "topic_ids": ["stat_test"], "keywords": ["假设检验"]},
    ],
    2019: [
        {"q_num": 1, "type": "选择题", "topic_ids": ["limit_inf_compare"], "keywords": ["无穷小阶数", "泰勒"]},
        {"q_num": 2, "type": "选择题", "topic_ids": ["derivative_def"], "keywords": ["可导", "左右导数"]},
        {"q_num": 3, "type": "选择题", "topic_ids": ["limit_seq_criteria"], "keywords": ["单调有界"]},
        {"q_num": 4, "type": "选择题", "topic_ids": ["line_int2"], "keywords": ["路径无关", "偏导"]},
        {"q_num": 5, "type": "选择题", "topic_ids": ["eigen_basic"], "keywords": ["特征值", "矩阵方程"]},
        {"q_num": 6, "type": "选择题", "topic_ids": ["linear_system"], "keywords": ["解结构", "基础解系"]},
        {"q_num": 7, "type": "选择题", "topic_ids": ["prob_cond"], "keywords": ["概率运算"]},
        {"q_num": 8, "type": "选择题", "topic_ids": ["rv_continuous"], "keywords": ["正态分布", "独立"]},
        {"q_num": 9, "type": "填空题", "topic_ids": ["multi_chain"], "keywords": ["隐函数", "偏导数"]},
        {"q_num": 10, "type": "填空题", "topic_ids": ["ode_separable"], "keywords": ["可分离变量"]},
        {"q_num": 11, "type": "填空题", "topic_ids": ["series_const"], "keywords": ["级数敛散"]},
        {"q_num": 12, "type": "填空题", "topic_ids": ["double_int"], "keywords": ["二重积分", "对称性"]},
        {"q_num": 13, "type": "填空题", "topic_ids": ["vector_group"], "keywords": ["线性相关", "秩"]},
        {"q_num": 14, "type": "填空题", "topic_ids": ["rv_function"], "keywords": ["分布函数", "分段"]},
        {"q_num": 15, "type": "解答题", "topic_ids": ["derivative_app_monotonicity"], "keywords": ["函数性质", "方程根"]},
        {"q_num": 16, "type": "解答题", "topic_ids": ["defint_compute"], "keywords": ["定积分", "面积"]},
        {"q_num": 17, "type": "解答题", "topic_ids": ["line_int2"], "keywords": ["曲线积分", "格林公式"]},
        {"q_num": 18, "type": "解答题", "topic_ids": ["series_power"], "keywords": ["幂级数", "和函数"]},
        {"q_num": 19, "type": "解答题", "topic_ids": ["quadratic_form"], "keywords": ["二次型", "正交变换"]},
        {"q_num": 20, "type": "解答题", "topic_ids": ["rv_function"], "keywords": ["随机变量函数"]},
        {"q_num": 21, "type": "解答题", "topic_ids": ["stat_estimation"], "keywords": ["矩估计", "最大似然"]},
        {"q_num": 22, "type": "解答题", "topic_ids": ["stat_test"], "keywords": ["假设检验"]},
    ],
    2018: [
        {"q_num": 1, "type": "选择题", "topic_ids": ["derivative_def"], "keywords": ["可导", "绝对值"]},
        {"q_num": 2, "type": "选择题", "topic_ids": ["surface_int2"], "keywords": ["曲面积分", "投影"]},
        {"q_num": 3, "type": "选择题", "topic_ids": ["series_const"], "keywords": ["级数求和", "展式"]},
        {"q_num": 4, "type": "选择题", "topic_ids": ["defint_compute"], "keywords": ["定积分比较"]},
        {"q_num": 5, "type": "选择题", "topic_ids": ["matrix_ops"], "keywords": ["矩阵乘法", "可逆"]},
        {"q_num": 6, "type": "选择题", "topic_ids": ["matrix_rank"], "keywords": ["秩", "乘积"]},
        {"q_num": 7, "type": "选择题", "topic_ids": ["rv_continuous"], "keywords": ["概率密度"]},
        {"q_num": 8, "type": "选择题", "topic_ids": ["stat_sample"], "keywords": ["抽样分布"]},
        {"q_num": 9, "type": "填空题", "topic_ids": ["lhopital"], "keywords": ["洛必达", "极限"]},
        {"q_num": 10, "type": "填空题", "topic_ids": ["defint_ftc"], "keywords": ["变限积分", "分部"]},
        {"q_num": 11, "type": "填空题", "topic_ids": ["line_int2"], "keywords": ["曲线积分"]},
        {"q_num": 12, "type": "填空题", "topic_ids": ["line_int1"], "keywords": ["第一类曲线积分"]},
        {"q_num": 13, "type": "填空题", "topic_ids": ["eigen_basic"], "keywords": ["特征值", "特征向量"]},
        {"q_num": 14, "type": "填空题", "topic_ids": ["independence"], "keywords": ["独立性", "概率"]},
        {"q_num": 15, "type": "解答题", "topic_ids": ["limit_inf_compare"], "keywords": ["无穷小", "不定积分"]},
        {"q_num": 16, "type": "解答题", "topic_ids": ["defint_volume"], "keywords": ["旋转体体积"]},
        {"q_num": 17, "type": "解答题", "topic_ids": ["triple_int"], "keywords": ["三重积分", "球坐标"]},
        {"q_num": 18, "type": "解答题", "topic_ids": ["ode_linear_high"], "keywords": ["微分方程", "特解"]},
        {"q_num": 19, "type": "解答题", "topic_ids": ["eigen_similar"], "keywords": ["相似对角化"]},
        {"q_num": 20, "type": "解答题", "topic_ids": ["rv_function"], "keywords": ["二维分布", "独立性"]},
        {"q_num": 21, "type": "解答题", "topic_ids": ["stat_estimation"], "keywords": ["矩估计", "最大似然"]},
        {"q_num": 22, "type": "解答题", "topic_ids": ["stat_test"], "keywords": ["假设检验"]},
    ],
    2016: [
        {"q_num": 1, "type": "选择题", "topic_ids": ["improper"], "keywords": ["反常积分", "敛散性"]},
        {"q_num": 2, "type": "选择题", "topic_ids": ["derivative_def"], "keywords": ["导数定义", "原函数"]},
        {"q_num": 3, "type": "选择题", "topic_ids": ["ode_linear1"], "keywords": ["一阶线性", "微分方程"]},
        {"q_num": 4, "type": "选择题", "topic_ids": ["defint_compute"], "keywords": ["定积分", "比较"]},
        {"q_num": 5, "type": "选择题", "topic_ids": ["line_int2"], "keywords": ["曲线积分", "路径无关"]},
        {"q_num": 6, "type": "选择题", "topic_ids": ["double_int"], "keywords": ["二重积分", "极坐标"]},
        {"q_num": 7, "type": "选择题", "topic_ids": ["series_const"], "keywords": ["级数", "敛散性"]},
        {"q_num": 8, "type": "选择题", "topic_ids": ["eigen_similar"], "keywords": ["相似对角化"]},
        {"q_num": 9, "type": "填空题", "topic_ids": ["limit_inf_compare"], "keywords": ["无穷小", "极限"]},
        {"q_num": 10, "type": "填空题", "topic_ids": ["total_diff"], "keywords": ["全微分", "偏导"]},
        {"q_num": 11, "type": "填空题", "topic_ids": ["surface_int2"], "keywords": ["曲面积分", "高斯"]},
        {"q_num": 12, "type": "填空题", "topic_ids": ["ode_linear_high"], "keywords": ["微分方程", "特解"]},
        {"q_num": 13, "type": "填空题", "topic_ids": ["det_compute"], "keywords": ["行列式", "特征多项式"]},
        {"q_num": 14, "type": "填空题", "topic_ids": ["rv_continuous"], "keywords": ["正态分布", "概率"]},
        {"q_num": 15, "type": "解答题", "topic_ids": ["multi_int_app"], "keywords": ["曲面面积", "二重积分"]},
        {"q_num": 16, "type": "解答题", "topic_ids": ["series_power"], "keywords": ["幂级数", "收敛域"]},
        {"q_num": 17, "type": "解答题", "topic_ids": ["triple_int"], "keywords": ["三重积分", "柱坐标"]},
        {"q_num": 18, "type": "解答题", "topic_ids": ["ode_linear_high"], "keywords": ["微分方程", "解的结构"]},
        {"q_num": 19, "type": "解答题", "topic_ids": ["eigen_similar"], "keywords": ["正交对角化", "二次型"]},
        {"q_num": 20, "type": "解答题", "topic_ids": ["rv_function"], "keywords": ["随机变量函数", "分布"]},
        {"q_num": 21, "type": "解答题", "topic_ids": ["stat_estimation"], "keywords": ["最大似然", "矩估计"]},
    ],
    2015: [
        {"q_num": 1, "type": "选择题", "topic_ids": ["concavity_inflection"], "keywords": ["拐点", "凹凸性"]},
        {"q_num": 2, "type": "选择题", "topic_ids": ["defint_compute"], "keywords": ["定积分", "奇偶性"]},
        {"q_num": 3, "type": "选择题", "topic_ids": ["series_power"], "keywords": ["幂级数", "逐项积分"]},
        {"q_num": 4, "type": "选择题", "topic_ids": ["line_int2"], "keywords": ["曲线积分", "格林公式"]},
        {"q_num": 5, "type": "选择题", "topic_ids": ["linear_system"], "keywords": ["线性方程组", "通解"]},
        {"q_num": 6, "type": "选择题", "topic_ids": ["quadratic_form"], "keywords": ["二次型", "正交变换"]},
        {"q_num": 7, "type": "选择题", "topic_ids": ["prob_cond"], "keywords": ["条件概率"]},
        {"q_num": 8, "type": "选择题", "topic_ids": ["stat_estimation"], "keywords": ["估计量", "无偏性"]},
        {"q_num": 9, "type": "填空题", "topic_ids": ["lhopital"], "keywords": ["洛必达", "极限"]},
        {"q_num": 10, "type": "填空题", "topic_ids": ["defint_volume"], "keywords": ["旋转体体积"]},
        {"q_num": 11, "type": "填空题", "topic_ids": ["multi_chain"], "keywords": ["复合函数", "偏导数"]},
        {"q_num": 12, "type": "填空题", "topic_ids": ["triple_int"], "keywords": ["三重积分", "对称性"]},
        {"q_num": 13, "type": "填空题", "topic_ids": ["det_compute"], "keywords": ["行列式", "递推"]},
        {"q_num": 14, "type": "填空题", "topic_ids": ["cov_corr"], "keywords": ["相关系数", "协方差"]},
        {"q_num": 15, "type": "解答题", "topic_ids": ["mvt_rolle"], "keywords": ["中值定理", "证明"]},
        {"q_num": 16, "type": "解答题", "topic_ids": ["surface_int2"], "keywords": ["曲面积分", "高斯公式"]},
        {"q_num": 17, "type": "解答题", "topic_ids": ["series_fourier"], "keywords": ["傅里叶级数"]},
        {"q_num": 18, "type": "解答题", "topic_ids": ["multi_extrema"], "keywords": ["拉格朗日", "条件极值"]},
        {"q_num": 19, "type": "解答题", "topic_ids": ["linear_system"], "keywords": ["方程组", "参数讨论"]},
        {"q_num": 20, "type": "解答题", "topic_ids": ["multi_rv_func"], "keywords": ["二维分布", "独立性"]},
        {"q_num": 21, "type": "解答题", "topic_ids": ["stat_estimation"], "keywords": ["矩估计", "最大似然"]},
    ],
    2014: [
        {"q_num": 1, "type": "选择题", "topic_ids": ["asymptote"], "keywords": ["渐近线", "曲线"]},
        {"q_num": 2, "type": "选择题", "topic_ids": ["derivative_rules"], "keywords": ["隐函数", "求导"]},
        {"q_num": 3, "type": "选择题", "topic_ids": ["double_int"], "keywords": ["二重积分", "交换次序"]},
        {"q_num": 4, "type": "选择题", "topic_ids": ["taylor"], "keywords": ["泰勒公式", "积分近似"]},
        {"q_num": 5, "type": "选择题", "topic_ids": ["vector_group"], "keywords": ["线性无关", "向量组"]},
        {"q_num": 6, "type": "选择题", "topic_ids": ["matrix_rank"], "keywords": ["矩阵秩", "线性方程组"]},
        {"q_num": 7, "type": "选择题", "topic_ids": ["prob_classical"], "keywords": ["几何概型", "概率"]},
        {"q_num": 8, "type": "选择题", "topic_ids": ["stat_sample"], "keywords": ["抽样分布", "统计量"]},
        {"q_num": 9, "type": "填空题", "topic_ids": ["surface_curve"], "keywords": ["空间解析几何", "平面"]},
        {"q_num": 10, "type": "填空题", "topic_ids": ["ode_linear1"], "keywords": ["微分方程", "通解"]},
        {"q_num": 11, "type": "填空题", "topic_ids": ["ode_linear_high"], "keywords": ["微分方程", "特解"]},
        {"q_num": 12, "type": "填空题", "topic_ids": ["surface_int1"], "keywords": ["第一类曲面积分"]},
        {"q_num": 13, "type": "填空题", "topic_ids": ["cov_corr"], "keywords": ["方差", "协方差"]},
        {"q_num": 14, "type": "填空题", "topic_ids": ["stat_estimation"], "keywords": ["最大似然", "估计"]},
        {"q_num": 15, "type": "解答题", "topic_ids": ["limit_seq_criteria"], "keywords": ["数列极限", "夹逼定理"]},
        {"q_num": 16, "type": "解答题", "topic_ids": ["line_int2"], "keywords": ["曲线积分", "格林公式"]},
        {"q_num": 17, "type": "解答题", "topic_ids": ["series_power"], "keywords": ["幂级数", "收敛域"]},
        {"q_num": 18, "type": "解答题", "topic_ids": ["triple_int"], "keywords": ["三重积分", "球坐标"]},
        {"q_num": 19, "type": "解答题", "topic_ids": ["eigen_similar"], "keywords": ["正交对角化", "对称矩阵"]},
        {"q_num": 20, "type": "解答题", "topic_ids": ["rv_function"], "keywords": ["分布函数", "密度"]},
        {"q_num": 21, "type": "解答题", "topic_ids": ["stat_estimation"], "keywords": ["参数估计", "置信区间"]},
    ],
    2013: [
        {"q_num": 1, "type": "选择题", "topic_ids": ["limit_inf_compare"], "keywords": ["无穷小比较", "高阶"]},
        {"q_num": 2, "type": "选择题", "topic_ids": ["line_int2"], "keywords": ["曲线积分", "路径无关"]},
        {"q_num": 3, "type": "选择题", "topic_ids": ["series_power"], "keywords": ["幂级数", "收敛域"]},
        {"q_num": 4, "type": "选择题", "topic_ids": ["defint_compute"], "keywords": ["定积分", "旋转体"]},
        {"q_num": 5, "type": "选择题", "topic_ids": ["matrix_rank"], "keywords": ["矩阵秩", "方程组"]},
        {"q_num": 6, "type": "选择题", "topic_ids": ["matrix_ops"], "keywords": ["矩阵运算", "伴随矩阵"]},
        {"q_num": 7, "type": "选择题", "topic_ids": ["rv_continuous"], "keywords": ["正态分布", "概率"]},
        {"q_num": 8, "type": "选择题", "topic_ids": ["cov_corr"], "keywords": ["相关系数", "独立"]},
        {"q_num": 9, "type": "填空题", "topic_ids": ["line_int1"], "keywords": ["曲线积分", "弧长"]},
        {"q_num": 10, "type": "填空题", "topic_ids": ["ode_linear_high"], "keywords": ["常系数方程", "通解"]},
        {"q_num": 11, "type": "填空题", "topic_ids": ["defint_compute"], "keywords": ["定积分", "周期函数"]},
        {"q_num": 12, "type": "填空题", "topic_ids": ["series_power"], "keywords": ["幂级数", "和函数"]},
        {"q_num": 13, "type": "填空题", "topic_ids": ["det_compute"], "keywords": ["行列式", "特征值"]},
        {"q_num": 14, "type": "填空题", "topic_ids": ["stat_estimation"], "keywords": ["最大似然", "矩估计"]},
        {"q_num": 15, "type": "解答题", "topic_ids": ["multi_chain"], "keywords": ["偏导数", "复合函数"]},
        {"q_num": 16, "type": "解答题", "topic_ids": ["double_int"], "keywords": ["二重积分", "极坐标"]},
        {"q_num": 17, "type": "解答题", "topic_ids": ["surface_int2"], "keywords": ["曲面积分", "斯托克斯"]},
        {"q_num": 18, "type": "解答题", "topic_ids": ["multi_extrema"], "keywords": ["拉格朗日乘数法"]},
        {"q_num": 19, "type": "解答题", "topic_ids": ["eigen_similar"], "keywords": ["正交对角化"]},
        {"q_num": 20, "type": "解答题", "topic_ids": ["rv_function"], "keywords": ["随机变量函数"]},
        {"q_num": 21, "type": "解答题", "topic_ids": ["lln"], "keywords": ["大数定律", "切比雪夫"]},
    ],
    2012: [
        {"q_num": 1, "type": "选择题", "topic_ids": ["asymptote"], "keywords": ["渐近线", "曲线"]},
        {"q_num": 2, "type": "选择题", "topic_ids": ["derivative_rules"], "keywords": ["复合函数", "求导"]},
        {"q_num": 3, "type": "选择题", "topic_ids": ["continuity"], "keywords": ["连续性", "可导"]},
        {"q_num": 4, "type": "选择题", "topic_ids": ["improper"], "keywords": ["反常积分", "敛散性"]},
        {"q_num": 5, "type": "选择题", "topic_ids": ["ode_linear1"], "keywords": ["微分方程", "解结构"]},
        {"q_num": 6, "type": "选择题", "topic_ids": ["series_power"], "keywords": ["幂级数", "和函数"]},
        {"q_num": 7, "type": "选择题", "topic_ids": ["vector_group"], "keywords": ["线性无关", "秩"]},
        {"q_num": 8, "type": "选择题", "topic_ids": ["rv_function"], "keywords": ["分布函数"]},
        {"q_num": 9, "type": "填空题", "topic_ids": ["multi_chain"], "keywords": ["偏导数", "全微分"]},
        {"q_num": 10, "type": "填空题", "topic_ids": ["ode_linear_high"], "keywords": ["微分方程", "特解"]},
        {"q_num": 11, "type": "填空题", "topic_ids": ["directional_gradient"], "keywords": ["方向导数", "梯度"]},
        {"q_num": 12, "type": "填空题", "topic_ids": ["surface_int2"], "keywords": ["曲面积分"]},
        {"q_num": 13, "type": "填空题", "topic_ids": ["det_compute"], "keywords": ["行列式", "范德蒙德"]},
        {"q_num": 14, "type": "填空题", "topic_ids": ["prob_classical"], "keywords": ["古典概型"]},
        {"q_num": 15, "type": "解答题", "topic_ids": ["limit_seq_criteria"], "keywords": ["夹逼定理", "单调有界"]},
        {"q_num": 16, "type": "解答题", "topic_ids": ["multi_extrema"], "keywords": ["条件极值", "拉格朗日"]},
        {"q_num": 17, "type": "解答题", "topic_ids": ["series_power"], "keywords": ["幂级数", "收敛区间"]},
        {"q_num": 18, "type": "解答题", "topic_ids": ["line_int2"], "keywords": ["曲线积分", "格林公式"]},
        {"q_num": 19, "type": "解答题", "topic_ids": ["eigen_similar"], "keywords": ["正交对角化"]},
        {"q_num": 20, "type": "解答题", "topic_ids": ["rv_discrete"], "keywords": ["离散分布", "联合分布"]},
        {"q_num": 21, "type": "解答题", "topic_ids": ["stat_estimation"], "keywords": ["最大似然估计"]},
    ],
    2011: [
        {"q_num": 1, "type": "选择题", "topic_ids": ["concavity_inflection"], "keywords": ["拐点", "凹凸性"]},
        {"q_num": 2, "type": "选择题", "topic_ids": ["series_power"], "keywords": ["幂级数", "收敛域"]},
        {"q_num": 3, "type": "选择题", "topic_ids": ["defint_compute"], "keywords": ["定积分", "比较"]},
        {"q_num": 4, "type": "选择题", "topic_ids": ["ode_linear_high"], "keywords": ["常系数方程", "特解"]},
        {"q_num": 5, "type": "选择题", "topic_ids": ["line_int2"], "keywords": ["曲线积分", "格林"]},
        {"q_num": 6, "type": "选择题", "topic_ids": ["linear_system"], "keywords": ["线性方程组", "解结构"]},
        {"q_num": 7, "type": "选择题", "topic_ids": ["matrix_inverse"], "keywords": ["逆矩阵", "秩"]},
        {"q_num": 8, "type": "选择题", "topic_ids": ["rv_discrete"], "keywords": ["二项分布", "期望"]},
        {"q_num": 9, "type": "填空题", "topic_ids": ["defint_compute"], "keywords": ["定积分", "弧长"]},
        {"q_num": 10, "type": "填空题", "topic_ids": ["ode_linear_high"], "keywords": ["微分方程", "特解形式"]},
        {"q_num": 11, "type": "填空题", "topic_ids": ["multi_chain"], "keywords": ["偏导数", "链式法则"]},
        {"q_num": 12, "type": "填空题", "topic_ids": ["surface_int2"], "keywords": ["曲面积分", "高斯"]},
        {"q_num": 13, "type": "填空题", "topic_ids": ["eigen_basic"], "keywords": ["特征值", "特征向量"]},
        {"q_num": 14, "type": "填空题", "topic_ids": ["stat_estimation"], "keywords": ["矩估计", "无偏性"]},
        {"q_num": 15, "type": "解答题", "topic_ids": ["lhopital"], "keywords": ["洛必达", "极限"]},
        {"q_num": 16, "type": "解答题", "topic_ids": ["double_int"], "keywords": ["二重积分", "交换次序"]},
        {"q_num": 17, "type": "解答题", "topic_ids": ["surface_int2"], "keywords": ["曲面积分", "高斯公式"]},
        {"q_num": 18, "type": "解答题", "topic_ids": ["series_power"], "keywords": ["幂级数", "和函数"]},
        {"q_num": 19, "type": "解答题", "topic_ids": ["eigen_similar"], "keywords": ["正交对角化"]},
        {"q_num": 20, "type": "解答题", "topic_ids": ["rv_function"], "keywords": ["正态分布", "独立"]},
        {"q_num": 21, "type": "解答题", "topic_ids": ["stat_estimation"], "keywords": ["最大似然", "矩估计"]},
    ],
    2009: [
        {"q_num": 1, "type": "选择题", "topic_ids": ["limit_ops"], "keywords": ["极限运算", "等价替换"]},
        {"q_num": 2, "type": "选择题", "topic_ids": ["multi_chain"], "keywords": ["偏导数", "复合函数"]},
        {"q_num": 3, "type": "选择题", "topic_ids": ["series_const"], "keywords": ["级数敛散性", "p级数"]},
        {"q_num": 4, "type": "选择题", "topic_ids": ["double_int"], "keywords": ["二重积分", "交换次序"]},
        {"q_num": 5, "type": "选择题", "topic_ids": ["linear_system"], "keywords": ["线性方程组", "通解"]},
        {"q_num": 6, "type": "选择题", "topic_ids": ["eigen_basic"], "keywords": ["特征值", "特征向量"]},
        {"q_num": 7, "type": "选择题", "topic_ids": ["prob_classical"], "keywords": ["古典概型", "排列组合"]},
        {"q_num": 8, "type": "选择题", "topic_ids": ["stat_sample"], "keywords": ["统计量", "抽样分布"]},
        {"q_num": 9, "type": "填空题", "topic_ids": ["ode_linear1"], "keywords": ["微分方程", "通解"]},
        {"q_num": 10, "type": "填空题", "topic_ids": ["line_int2"], "keywords": ["曲线积分", "格林公式"]},
        {"q_num": 11, "type": "填空题", "topic_ids": ["surface_int2"], "keywords": ["曲面积分", "高斯"]},
        {"q_num": 12, "type": "填空题", "topic_ids": ["series_power"], "keywords": ["幂级数", "收敛半径"]},
        {"q_num": 13, "type": "填空题", "topic_ids": ["det_compute"], "keywords": ["行列式", "特征值"]},
        {"q_num": 14, "type": "填空题", "topic_ids": ["expectation"], "keywords": ["期望", "二项分布"]},
        {"q_num": 15, "type": "解答题", "topic_ids": ["limit_seq_criteria"], "keywords": ["数列极限", "单调"]},
        {"q_num": 16, "type": "解答题", "topic_ids": ["multi_extrema"], "keywords": ["拉格朗日", "条件极值"]},
        {"q_num": 17, "type": "解答题", "topic_ids": ["triple_int"], "keywords": ["三重积分", "柱坐标"]},
        {"q_num": 18, "type": "解答题", "topic_ids": ["ode_linear_high"], "keywords": ["微分方程", "解结构"]},
        {"q_num": 19, "type": "解答题", "topic_ids": ["eigen_similar"], "keywords": ["正交对角化"]},
        {"q_num": 20, "type": "解答题", "topic_ids": ["rv_function"], "keywords": ["随机变量函数"]},
        {"q_num": 21, "type": "解答题", "topic_ids": ["stat_estimation"], "keywords": ["矩估计", "最大似然"]},
    ],
    2008: [
        {"q_num": 1, "type": "选择题", "topic_ids": ["concavity_inflection"], "keywords": ["拐点"]},
        {"q_num": 2, "type": "选择题", "topic_ids": ["double_int"], "keywords": ["二重积分", "极坐标"]},
        {"q_num": 3, "type": "选择题", "topic_ids": ["series_fourier"], "keywords": ["傅里叶级数", "和函数"]},
        {"q_num": 4, "type": "选择题", "topic_ids": ["mvt_lagrange"], "keywords": ["中值定理", "极限"]},
        {"q_num": 5, "type": "选择题", "topic_ids": ["matrix_rank"], "keywords": ["矩阵秩", "可逆"]},
        {"q_num": 6, "type": "选择题", "topic_ids": ["linear_system"], "keywords": ["线性方程组", "解结构"]},
        {"q_num": 7, "type": "选择题", "topic_ids": ["rv_discrete"], "keywords": ["离散分布", "二项"]},
        {"q_num": 8, "type": "选择题", "topic_ids": ["rv_continuous"], "keywords": ["正态分布", "标准化"]},
        {"q_num": 9, "type": "填空题", "topic_ids": ["ode_linear_high"], "keywords": ["微分方程", "通解"]},
        {"q_num": 10, "type": "填空题", "topic_ids": ["defint_compute"], "keywords": ["定积分", "曲线切线"]},
        {"q_num": 11, "type": "填空题", "topic_ids": ["line_int1"], "keywords": ["曲线积分", "弧长"]},
        {"q_num": 12, "type": "填空题", "topic_ids": ["series_power"], "keywords": ["幂级数", "逐项积分"]},
        {"q_num": 13, "type": "填空题", "topic_ids": ["eigen_basic"], "keywords": ["特征值", "特征向量"]},
        {"q_num": 14, "type": "填空题", "topic_ids": ["rv_discrete"], "keywords": ["离散分布", "期望"]},
        {"q_num": 15, "type": "解答题", "topic_ids": ["limit_seq_criteria"], "keywords": ["数列极限", "单调有界"]},
        {"q_num": 16, "type": "解答题", "topic_ids": ["surface_int2"], "keywords": ["曲面积分", "高斯"]},
        {"q_num": 17, "type": "解答题", "topic_ids": ["double_int"], "keywords": ["二重积分", "对称性"]},
        {"q_num": 18, "type": "解答题", "topic_ids": ["series_power"], "keywords": ["幂级数", "收敛域"]},
        {"q_num": 19, "type": "解答题", "topic_ids": ["multi_extrema"], "keywords": ["极值", "参数方程"]},
        {"q_num": 20, "type": "解答题", "topic_ids": ["eigen_similar"], "keywords": ["正交对角化", "二次型"]},
        {"q_num": 21, "type": "解答题", "topic_ids": ["stat_estimation"], "keywords": ["参数估计", "置信区间"]},
    ],
    2007: [
        {"q_num": 1, "type": "选择题", "topic_ids": ["limit_inf_compare"], "keywords": ["无穷小比较", "等价"]},
        {"q_num": 2, "type": "选择题", "topic_ids": ["asymptote"], "keywords": ["渐近线"]},
        {"q_num": 3, "type": "选择题", "topic_ids": ["ode_reducible"], "keywords": ["微分方程", "降阶"]},
        {"q_num": 4, "type": "选择题", "topic_ids": ["lhopital"], "keywords": ["洛必达", "极限"]},
        {"q_num": 5, "type": "选择题", "topic_ids": ["matrix_inverse"], "keywords": ["逆矩阵", "行列式"]},
        {"q_num": 6, "type": "选择题", "topic_ids": ["vector_group"], "keywords": ["线性无关", "秩"]},
        {"q_num": 7, "type": "选择题", "topic_ids": ["rv_discrete"], "keywords": ["离散分布", "概率"]},
        {"q_num": 8, "type": "选择题", "topic_ids": ["stat_sample"], "keywords": ["统计量", "卡方分布"]},
        {"q_num": 9, "type": "填空题", "topic_ids": ["defint_compute"], "keywords": ["定积分", "奇偶性"]},
        {"q_num": 10, "type": "填空题", "topic_ids": ["ode_linear_high"], "keywords": ["微分方程", "特解形式"]},
        {"q_num": 11, "type": "填空题", "topic_ids": ["surface_int2"], "keywords": ["曲面积分", "高斯"]},
        {"q_num": 12, "type": "填空题", "topic_ids": ["series_power"], "keywords": ["幂级数", "和函数"]},
        {"q_num": 13, "type": "填空题", "topic_ids": ["det_compute"], "keywords": ["行列式", "范德蒙德"]},
        {"q_num": 14, "type": "填空题", "topic_ids": ["cov_corr"], "keywords": ["相关系数", "协方差"]},
        {"q_num": 15, "type": "解答题", "topic_ids": ["double_int"], "keywords": ["二重积分", "极坐标"]},
        {"q_num": 16, "type": "解答题", "topic_ids": ["series_power"], "keywords": ["幂级数", "逐项求导"]},
        {"q_num": 17, "type": "解答题", "topic_ids": ["line_int2"], "keywords": ["曲线积分", "格林公式"]},
        {"q_num": 18, "type": "解答题", "topic_ids": ["multi_extrema"], "keywords": ["条件极值", "拉格朗日"]},
        {"q_num": 19, "type": "解答题", "topic_ids": ["eigen_similar"], "keywords": ["正交对角化"]},
        {"q_num": 20, "type": "解答题", "topic_ids": ["rv_function"], "keywords": ["二维分布", "边缘密度"]},
        {"q_num": 21, "type": "解答题", "topic_ids": ["stat_estimation"], "keywords": ["矩估计", "最大似然"]},
    ],
    2006: [
        {"q_num": 1, "type": "选择题", "topic_ids": ["lhopital"], "keywords": ["洛必达", "极限"]},
        {"q_num": 2, "type": "选择题", "topic_ids": ["derivative_app_monotonicity"], "keywords": ["导数应用", "单调性"]},
        {"q_num": 3, "type": "选择题", "topic_ids": ["improper"], "keywords": ["反常积分", "敛散性"]},
        {"q_num": 4, "type": "选择题", "topic_ids": ["multi_chain"], "keywords": ["偏导数", "全微分"]},
        {"q_num": 5, "type": "选择题", "topic_ids": ["matrix_ops"], "keywords": ["矩阵运算", "逆矩阵"]},
        {"q_num": 6, "type": "选择题", "topic_ids": ["linear_system"], "keywords": ["线性方程组", "解"]},
        {"q_num": 7, "type": "选择题", "topic_ids": ["prob_classical"], "keywords": ["古典概型"]},
        {"q_num": 8, "type": "选择题", "topic_ids": ["rv_continuous"], "keywords": ["正态分布", "独立性"]},
        {"q_num": 9, "type": "填空题", "topic_ids": ["limit_inf_small"], "keywords": ["无穷小", "极限"]},
        {"q_num": 10, "type": "填空题", "topic_ids": ["ode_linear1"], "keywords": ["一阶微分方程"]},
        {"q_num": 11, "type": "填空题", "topic_ids": ["line_int2"], "keywords": ["曲线积分", "格林"]},
        {"q_num": 12, "type": "填空题", "topic_ids": ["series_const"], "keywords": ["级数敛散性"]},
        {"q_num": 13, "type": "填空题", "topic_ids": ["det_compute"], "keywords": ["行列式", "特征值"]},
        {"q_num": 14, "type": "填空题", "topic_ids": ["rv_discrete"], "keywords": ["二项分布", "期望"]},
        {"q_num": 15, "type": "解答题", "topic_ids": ["limit_seq_criteria"], "keywords": ["数列极限", "单调有界"]},
        {"q_num": 16, "type": "解答题", "topic_ids": ["double_int"], "keywords": ["二重积分", "极坐标"]},
        {"q_num": 17, "type": "解答题", "topic_ids": ["series_power"], "keywords": ["幂级数", "收敛域"]},
        {"q_num": 18, "type": "解答题", "topic_ids": ["triple_int"], "keywords": ["三重积分", "球坐标"]},
        {"q_num": 19, "type": "解答题", "topic_ids": ["eigen_similar"], "keywords": ["正交对角化"]},
        {"q_num": 20, "type": "解答题", "topic_ids": ["rv_function"], "keywords": ["随机变量函数"]},
        {"q_num": 21, "type": "解答题", "topic_ids": ["stat_estimation"], "keywords": ["矩估计", "最大似然"]},
    ],
    2005: [
        {"q_num": 1, "type": "选择题", "topic_ids": ["asymptote"], "keywords": ["渐近线"]},
        {"q_num": 2, "type": "选择题", "topic_ids": ["ode_linear1"], "keywords": ["微分方程", "解结构"]},
        {"q_num": 3, "type": "选择题", "topic_ids": ["series_power"], "keywords": ["幂级数", "收敛域"]},
        {"q_num": 4, "type": "选择题", "topic_ids": ["limit_inf_compare"], "keywords": ["无穷小比较"]},
        {"q_num": 5, "type": "选择题", "topic_ids": ["matrix_rank"], "keywords": ["矩阵秩"]},
        {"q_num": 6, "type": "选择题", "topic_ids": ["eigen_basic"], "keywords": ["特征值", "特征向量"]},
        {"q_num": 7, "type": "选择题", "topic_ids": ["prob_classical"], "keywords": ["古典概型"]},
        {"q_num": 8, "type": "选择题", "topic_ids": ["stat_estimation"], "keywords": ["估计量", "无偏性"]},
        {"q_num": 9, "type": "填空题", "topic_ids": ["defint_compute"], "keywords": ["定积分", "分部"]},
        {"q_num": 10, "type": "填空题", "topic_ids": ["surface_int2"], "keywords": ["曲面积分"]},
        {"q_num": 11, "type": "填空题", "topic_ids": ["line_int2"], "keywords": ["曲线积分", "路径无关"]},
        {"q_num": 12, "type": "填空题", "topic_ids": ["multi_chain"], "keywords": ["偏导数", "复合函数"]},
        {"q_num": 13, "type": "填空题", "topic_ids": ["det_compute"], "keywords": ["行列式"]},
        {"q_num": 14, "type": "填空题", "topic_ids": ["cov_corr"], "keywords": ["协方差", "相关系数"]},
        {"q_num": 15, "type": "解答题", "topic_ids": ["taylor"], "keywords": ["泰勒公式", "极限"]},
        {"q_num": 16, "type": "解答题", "topic_ids": ["double_int"], "keywords": ["二重积分", "交换次序"]},
        {"q_num": 17, "type": "解答题", "topic_ids": ["series_power"], "keywords": ["幂级数", "和函数"]},
        {"q_num": 18, "type": "解答题", "topic_ids": ["triple_int"], "keywords": ["三重积分", "球坐标"]},
        {"q_num": 19, "type": "解答题", "topic_ids": ["eigen_similar"], "keywords": ["正交对角化"]},
        {"q_num": 20, "type": "解答题", "topic_ids": ["rv_function"], "keywords": ["随机变量函数"]},
        {"q_num": 21, "type": "解答题", "topic_ids": ["stat_estimation"], "keywords": ["最大似然", "矩估计"]},
    ],
    2003: [
        {"q_num": 1, "type": "选择题", "topic_ids": ["limit_ops"], "keywords": ["极限运算"]},
        {"q_num": 2, "type": "选择题", "topic_ids": ["continuity"], "keywords": ["连续性", "间断点"]},
        {"q_num": 3, "type": "选择题", "topic_ids": ["defint_compute"], "keywords": ["定积分"]},
        {"q_num": 4, "type": "选择题", "topic_ids": ["series_const"], "keywords": ["级数", "敛散性"]},
        {"q_num": 5, "type": "选择题", "topic_ids": ["matrix_inverse"], "keywords": ["逆矩阵"]},
        {"q_num": 6, "type": "选择题", "topic_ids": ["vector_group"], "keywords": ["线性无关"]},
        {"q_num": 7, "type": "填空题", "topic_ids": ["ode_linear1"], "keywords": ["微分方程"]},
        {"q_num": 8, "type": "填空题", "topic_ids": ["defint_physics"], "keywords": ["应用", "平均值"]},
        {"q_num": 9, "type": "填空题", "topic_ids": ["double_int"], "keywords": ["二重积分"]},
        {"q_num": 10, "type": "填空题", "topic_ids": ["det_compute"], "keywords": ["行列式"]},
        {"q_num": 11, "type": "解答题", "topic_ids": ["multi_chain"], "keywords": ["偏导数"]},
        {"q_num": 12, "type": "解答题", "topic_ids": ["series_power"], "keywords": ["幂级数", "和函数"]},
        {"q_num": 13, "type": "解答题", "topic_ids": ["triple_int"], "keywords": ["三重积分"]},
        {"q_num": 14, "type": "解答题", "topic_ids": ["eigen_similar"], "keywords": ["对角化"]},
        {"q_num": 15, "type": "解答题", "topic_ids": ["rv_function"], "keywords": ["随机变量函数"]},
        {"q_num": 16, "type": "解答题", "topic_ids": ["stat_estimation"], "keywords": ["最大似然"]},
    ],
    2002: [
        {"q_num": 1, "type": "选择题", "topic_ids": ["improper"], "keywords": ["反常积分"]},
        {"q_num": 2, "type": "选择题", "topic_ids": ["multi_chain"], "keywords": ["偏导数"]},
        {"q_num": 3, "type": "选择题", "topic_ids": ["series_const"], "keywords": ["级数敛散"]},
        {"q_num": 4, "type": "选择题", "topic_ids": ["linear_system"], "keywords": ["方程组"]},
        {"q_num": 5, "type": "选择题", "topic_ids": ["eigen_basic"], "keywords": ["特征值"]},
        {"q_num": 6, "type": "填空题", "topic_ids": ["ode_linear_high"], "keywords": ["微分方程"]},
        {"q_num": 7, "type": "填空题", "topic_ids": ["defint_volume"], "keywords": ["旋转体体积"]},
        {"q_num": 8, "type": "填空题", "topic_ids": ["series_power"], "keywords": ["幂级数"]},
        {"q_num": 9, "type": "填空题", "topic_ids": ["det_compute"], "keywords": ["行列式"]},
        {"q_num": 10, "type": "解答题", "topic_ids": ["taylor"], "keywords": ["泰勒公式"]},
        {"q_num": 11, "type": "解答题", "topic_ids": ["line_int2"], "keywords": ["曲线积分"]},
        {"q_num": 12, "type": "解答题", "topic_ids": ["surface_int2"], "keywords": ["曲面积分"]},
        {"q_num": 13, "type": "解答题", "topic_ids": ["double_int"], "keywords": ["二重积分"]},
        {"q_num": 14, "type": "解答题", "topic_ids": ["eigen_similar"], "keywords": ["对角化"]},
        {"q_num": 15, "type": "解答题", "topic_ids": ["rv_discrete"], "keywords": ["离散分布"]},
    ],
    2001: [
        {"q_num": 1, "type": "选择题", "topic_ids": ["limit_inf_compare"], "keywords": ["无穷小"]},
        {"q_num": 2, "type": "选择题", "topic_ids": ["lhopital"], "keywords": ["洛必达"]},
        {"q_num": 3, "type": "选择题", "topic_ids": ["series_power"], "keywords": ["幂级数"]},
        {"q_num": 4, "type": "选择题", "topic_ids": ["linear_system"], "keywords": ["方程组"]},
        {"q_num": 5, "type": "选择题", "topic_ids": ["matrix_ops"], "keywords": ["矩阵运算"]},
        {"q_num": 6, "type": "填空题", "topic_ids": ["ode_linear_high"], "keywords": ["微分方程"]},
        {"q_num": 7, "type": "填空题", "topic_ids": ["defint_compute"], "keywords": ["定积分"]},
        {"q_num": 8, "type": "填空题", "topic_ids": ["line_int2"], "keywords": ["曲线积分"]},
        {"q_num": 9, "type": "填空题", "topic_ids": ["det_compute"], "keywords": ["行列式"]},
        {"q_num": 10, "type": "解答题", "topic_ids": ["limit_seq_criteria"], "keywords": ["数列极限"]},
        {"q_num": 11, "type": "解答题", "topic_ids": ["surface_int2"], "keywords": ["曲面积分"]},
        {"q_num": 12, "type": "解答题", "topic_ids": ["series_power"], "keywords": ["幂级数"]},
        {"q_num": 13, "type": "解答题", "topic_ids": ["eigen_similar"], "keywords": ["对角化"]},
        {"q_num": 14, "type": "解答题", "topic_ids": ["rv_discrete"], "keywords": ["离散分布"]},
    ],
    2000: [
        {"q_num": 1, "type": "选择题", "topic_ids": ["continuity"], "keywords": ["连续"]},
        {"q_num": 2, "type": "选择题", "topic_ids": ["double_int"], "keywords": ["二重积分"]},
        {"q_num": 3, "type": "选择题", "topic_ids": ["series_const"], "keywords": ["级数"]},
        {"q_num": 4, "type": "选择题", "topic_ids": ["vector_group"], "keywords": ["线性相关"]},
        {"q_num": 5, "type": "填空题", "topic_ids": ["limit_important"], "keywords": ["重要极限"]},
        {"q_num": 6, "type": "填空题", "topic_ids": ["line_int2"], "keywords": ["曲线积分"]},
        {"q_num": 7, "type": "填空题", "topic_ids": ["ode_linear_high"], "keywords": ["微分方程"]},
        {"q_num": 8, "type": "填空题", "topic_ids": ["det_compute"], "keywords": ["行列式"]},
        {"q_num": 9, "type": "解答题", "topic_ids": ["multi_chain"], "keywords": ["偏导数"]},
        {"q_num": 10, "type": "解答题", "topic_ids": ["triple_int"], "keywords": ["三重积分"]},
        {"q_num": 11, "type": "解答题", "topic_ids": ["series_power"], "keywords": ["幂级数"]},
        {"q_num": 12, "type": "解答题", "topic_ids": ["eigen_similar"], "keywords": ["对角化"]},
        {"q_num": 13, "type": "解答题", "topic_ids": ["rv_discrete"], "keywords": ["离散分布"]},
    ],
    1999: [
        {"q_num": 1, "type": "选择题", "topic_ids": ["derivative_def"], "keywords": ["可导"]},
        {"q_num": 2, "type": "选择题", "topic_ids": ["surface_int2"], "keywords": ["曲面积分"]},
        {"q_num": 3, "type": "选择题", "topic_ids": ["series_power"], "keywords": ["幂级数"]},
        {"q_num": 4, "type": "选择题", "topic_ids": ["linear_system"], "keywords": ["方程组"]},
        {"q_num": 5, "type": "填空题", "topic_ids": ["limit_important"], "keywords": ["重要极限"]},
        {"q_num": 6, "type": "填空题", "topic_ids": ["ode_linear1"], "keywords": ["微分方程"]},
        {"q_num": 7, "type": "填空题", "topic_ids": ["det_compute"], "keywords": ["行列式"]},
        {"q_num": 8, "type": "解答题", "topic_ids": ["multi_chain"], "keywords": ["偏导数"]},
        {"q_num": 9, "type": "解答题", "topic_ids": ["line_int2"], "keywords": ["曲线积分"]},
        {"q_num": 10, "type": "解答题", "topic_ids": ["double_int"], "keywords": ["二重积分"]},
        {"q_num": 11, "type": "解答题", "topic_ids": ["series_power"], "keywords": ["幂级数"]},
        {"q_num": 12, "type": "解答题", "topic_ids": ["eigen_similar"], "keywords": ["对角化"]},
    ],
    1998: [
        {"q_num": 1, "type": "选择题", "topic_ids": ["continuity"], "keywords": ["连续"]},
        {"q_num": 2, "type": "选择题", "topic_ids": ["defint_compute"], "keywords": ["定积分"]},
        {"q_num": 3, "type": "选择题", "topic_ids": ["series_const"], "keywords": ["级数"]},
        {"q_num": 4, "type": "选择题", "topic_ids": ["matrix_rank"], "keywords": ["秩"]},
        {"q_num": 5, "type": "填空题", "topic_ids": ["limit_important"], "keywords": ["重要极限"]},
        {"q_num": 6, "type": "填空题", "topic_ids": ["surface_int2"], "keywords": ["曲面积分"]},
        {"q_num": 7, "type": "填空题", "topic_ids": ["eigen_basic"], "keywords": ["特征值"]},
        {"q_num": 8, "type": "解答题", "topic_ids": ["multi_chain"], "keywords": ["偏导数"]},
        {"q_num": 9, "type": "解答题", "topic_ids": ["triple_int"], "keywords": ["三重积分"]},
        {"q_num": 10, "type": "解答题", "topic_ids": ["series_power"], "keywords": ["幂级数"]},
        {"q_num": 11, "type": "解答题", "topic_ids": ["eigen_similar"], "keywords": ["对角化"]},
    ],
    1996: [
        {"q_num": 1, "type": "选择题", "topic_ids": ["limit_inf_compare"], "keywords": ["无穷小比较"]},
        {"q_num": 2, "type": "选择题", "topic_ids": ["improper"], "keywords": ["反常积分"]},
        {"q_num": 3, "type": "选择题", "topic_ids": ["series_const"], "keywords": ["级数敛散"]},
        {"q_num": 4, "type": "选择题", "topic_ids": ["eigen_basic"], "keywords": ["特征值"]},
        {"q_num": 5, "type": "填空题", "topic_ids": ["ode_linear_high"], "keywords": ["微分方程"]},
        {"q_num": 6, "type": "填空题", "topic_ids": ["line_int2"], "keywords": ["曲线积分"]},
        {"q_num": 7, "type": "填空题", "topic_ids": ["det_compute"], "keywords": ["行列式"]},
        {"q_num": 8, "type": "解答题", "topic_ids": ["multi_chain"], "keywords": ["偏导数"]},
        {"q_num": 9, "type": "解答题", "topic_ids": ["double_int"], "keywords": ["二重积分"]},
        {"q_num": 10, "type": "解答题", "topic_ids": ["series_power"], "keywords": ["幂级数"]},
        {"q_num": 11, "type": "解答题", "topic_ids": ["eigen_similar"], "keywords": ["对角化"]},
    ],
    1995: [
        {"q_num": 1, "type": "选择题", "topic_ids": ["lhopital"], "keywords": ["洛必达"]},
        {"q_num": 2, "type": "选择题", "topic_ids": ["double_int"], "keywords": ["二重积分"]},
        {"q_num": 3, "type": "选择题", "topic_ids": ["series_power"], "keywords": ["幂级数"]},
        {"q_num": 4, "type": "选择题", "topic_ids": ["matrix_ops"], "keywords": ["矩阵运算"]},
        {"q_num": 5, "type": "填空题", "topic_ids": ["limit_important"], "keywords": ["重要极限"]},
        {"q_num": 6, "type": "填空题", "topic_ids": ["surface_int2"], "keywords": ["曲面积分"]},
        {"q_num": 7, "type": "填空题", "topic_ids": ["det_compute"], "keywords": ["行列式"]},
        {"q_num": 8, "type": "解答题", "topic_ids": ["multi_chain"], "keywords": ["偏导数"]},
        {"q_num": 9, "type": "解答题", "topic_ids": ["triple_int"], "keywords": ["三重积分"]},
        {"q_num": 10, "type": "解答题", "topic_ids": ["series_power"], "keywords": ["幂级数"]},
        {"q_num": 11, "type": "解答题", "topic_ids": ["eigen_similar"], "keywords": ["对角化"]},
    ],
    1994: [
        {"q_num": 1, "type": "选择题", "topic_ids": ["continuity"], "keywords": ["连续"]},
        {"q_num": 2, "type": "选择题", "topic_ids": ["series_const"], "keywords": ["级数"]},
        {"q_num": 3, "type": "选择题", "topic_ids": ["double_int"], "keywords": ["二重积分"]},
        {"q_num": 4, "type": "选择题", "topic_ids": ["matrix_rank"], "keywords": ["秩"]},
        {"q_num": 5, "type": "填空题", "topic_ids": ["limit_important"], "keywords": ["重要极限"]},
        {"q_num": 6, "type": "填空题", "topic_ids": ["line_int2"], "keywords": ["曲线积分"]},
        {"q_num": 7, "type": "填空题", "topic_ids": ["det_compute"], "keywords": ["行列式"]},
        {"q_num": 8, "type": "解答题", "topic_ids": ["multi_chain"], "keywords": ["偏导数"]},
        {"q_num": 9, "type": "解答题", "topic_ids": ["surface_int2"], "keywords": ["曲面积分"]},
        {"q_num": 10, "type": "解答题", "topic_ids": ["triple_int"], "keywords": ["三重积分"]},
        {"q_num": 11, "type": "解答题", "topic_ids": ["series_power"], "keywords": ["幂级数"]},
        {"q_num": 12, "type": "解答题", "topic_ids": ["eigen_similar"], "keywords": ["对角化"]},
    ],
    1993: [
        {"q_num": 1, "type": "选择题", "topic_ids": ["limit_inf_small"], "keywords": ["无穷小"]},
        {"q_num": 2, "type": "选择题", "topic_ids": ["continuity"], "keywords": ["连续"]},
        {"q_num": 3, "type": "选择题", "topic_ids": ["series_const"], "keywords": ["级数"]},
        {"q_num": 4, "type": "填空题", "topic_ids": ["limit_ops"], "keywords": ["极限"]},
        {"q_num": 5, "type": "填空题", "topic_ids": ["defint_volume"], "keywords": ["旋转体"]},
        {"q_num": 6, "type": "填空题", "topic_ids": ["ode_linear1"], "keywords": ["微分方程"]},
        {"q_num": 7, "type": "填空题", "topic_ids": ["det_compute"], "keywords": ["行列式"]},
        {"q_num": 8, "type": "解答题", "topic_ids": ["double_int"], "keywords": ["二重积分"]},
        {"q_num": 9, "type": "解答题", "topic_ids": ["surface_int2"], "keywords": ["曲面积分"]},
        {"q_num": 10, "type": "解答题", "topic_ids": ["series_power"], "keywords": ["幂级数"]},
        {"q_num": 11, "type": "解答题", "topic_ids": ["eigen_similar"], "keywords": ["对角化"]},
    ],
    1992: [
        {"q_num": 1, "type": "选择题", "topic_ids": ["limit_inf_small"], "keywords": ["无穷小"]},
        {"q_num": 2, "type": "选择题", "topic_ids": ["defint_compute"], "keywords": ["定积分"]},
        {"q_num": 3, "type": "选择题", "topic_ids": ["series_const"], "keywords": ["级数"]},
        {"q_num": 4, "type": "填空题", "topic_ids": ["limit_important"], "keywords": ["重要极限"]},
        {"q_num": 5, "type": "填空题", "topic_ids": ["ode_linear_high"], "keywords": ["微分方程"]},
        {"q_num": 6, "type": "填空题", "topic_ids": ["det_compute"], "keywords": ["行列式"]},
        {"q_num": 7, "type": "解答题", "topic_ids": ["multi_chain"], "keywords": ["偏导数"]},
        {"q_num": 8, "type": "解答题", "topic_ids": ["triple_int"], "keywords": ["三重积分"]},
        {"q_num": 9, "type": "解答题", "topic_ids": ["series_power"], "keywords": ["幂级数"]},
        {"q_num": 10, "type": "解答题", "topic_ids": ["eigen_similar"], "keywords": ["对角化"]},
    ],
    1991: [
        {"q_num": 1, "type": "选择题", "topic_ids": ["derivative_app_monotonicity"], "keywords": ["单调性"]},
        {"q_num": 2, "type": "选择题", "topic_ids": ["series_const"], "keywords": ["级数"]},
        {"q_num": 3, "type": "选择题", "topic_ids": ["eigen_basic"], "keywords": ["特征值"]},
        {"q_num": 4, "type": "填空题", "topic_ids": ["defint_compute"], "keywords": ["定积分"]},
        {"q_num": 5, "type": "填空题", "topic_ids": ["ode_linear_high"], "keywords": ["微分方程"]},
        {"q_num": 6, "type": "填空题", "topic_ids": ["det_compute"], "keywords": ["行列式"]},
        {"q_num": 7, "type": "解答题", "topic_ids": ["double_int"], "keywords": ["二重积分"]},
        {"q_num": 8, "type": "解答题", "topic_ids": ["series_power"], "keywords": ["幂级数"]},
        {"q_num": 9, "type": "解答题", "topic_ids": ["eigen_similar"], "keywords": ["对角化"]},
    ],
    1990: [
        {"q_num": 1, "type": "选择题", "topic_ids": ["continuity"], "keywords": ["连续"]},
        {"q_num": 2, "type": "选择题", "topic_ids": ["series_const"], "keywords": ["级数"]},
        {"q_num": 3, "type": "填空题", "topic_ids": ["limit_important"], "keywords": ["重要极限"]},
        {"q_num": 4, "type": "填空题", "topic_ids": ["ode_linear1"], "keywords": ["微分方程"]},
        {"q_num": 5, "type": "填空题", "topic_ids": ["det_compute"], "keywords": ["行列式"]},
        {"q_num": 6, "type": "解答题", "topic_ids": ["double_int"], "keywords": ["二重积分"]},
        {"q_num": 7, "type": "解答题", "topic_ids": ["surface_int2"], "keywords": ["曲面积分"]},
        {"q_num": 8, "type": "解答题", "topic_ids": ["series_power"], "keywords": ["幂级数"]},
        {"q_num": 9, "type": "解答题", "topic_ids": ["eigen_similar"], "keywords": ["对角化"]},
    ],
    1989: [
        {"q_num": 1, "type": "选择题", "topic_ids": ["limit_ops"], "keywords": ["极限"]},
        {"q_num": 2, "type": "选择题", "topic_ids": ["series_const"], "keywords": ["级数"]},
        {"q_num": 3, "type": "填空题", "topic_ids": ["derivative_rules"], "keywords": ["求导"]},
        {"q_num": 4, "type": "填空题", "topic_ids": ["defint_compute"], "keywords": ["定积分"]},
        {"q_num": 5, "type": "填空题", "topic_ids": ["det_compute"], "keywords": ["行列式"]},
        {"q_num": 6, "type": "解答题", "topic_ids": ["multi_chain"], "keywords": ["偏导数"]},
        {"q_num": 7, "type": "解答题", "topic_ids": ["double_int"], "keywords": ["二重积分"]},
        {"q_num": 8, "type": "解答题", "topic_ids": ["triple_int"], "keywords": ["三重积分"]},
        {"q_num": 9, "type": "解答题", "topic_ids": ["eigen_similar"], "keywords": ["对角化"]},
    ],
    1988: [
        {"q_num": 1, "type": "选择题", "topic_ids": ["limit_ops"], "keywords": ["极限"]},
        {"q_num": 2, "type": "选择题", "topic_ids": ["series_const"], "keywords": ["级数"]},
        {"q_num": 3, "type": "填空题", "topic_ids": ["defint_compute"], "keywords": ["定积分"]},
        {"q_num": 4, "type": "填空题", "topic_ids": ["ode_linear1"], "keywords": ["微分方程"]},
        {"q_num": 5, "type": "填空题", "topic_ids": ["det_compute"], "keywords": ["行列式"]},
        {"q_num": 6, "type": "解答题", "topic_ids": ["double_int"], "keywords": ["二重积分"]},
        {"q_num": 7, "type": "解答题", "topic_ids": ["surface_int2"], "keywords": ["曲面积分"]},
        {"q_num": 8, "type": "解答题", "topic_ids": ["series_power"], "keywords": ["幂级数"]},
    ],
    1987: [
        {"q_num": 1, "type": "选择题", "topic_ids": ["limit_ops"], "keywords": ["极限"]},
        {"q_num": 2, "type": "选择题", "topic_ids": ["continuity"], "keywords": ["连续"]},
        {"q_num": 3, "type": "填空题", "topic_ids": ["defint_compute"], "keywords": ["定积分"]},
        {"q_num": 4, "type": "填空题", "topic_ids": ["ode_linear1"], "keywords": ["微分方程"]},
        {"q_num": 5, "type": "填空题", "topic_ids": ["det_compute"], "keywords": ["行列式"]},
        {"q_num": 6, "type": "解答题", "topic_ids": ["double_int"], "keywords": ["二重积分"]},
        {"q_num": 7, "type": "解答题", "topic_ids": ["surface_int2"], "keywords": ["曲面积分"]},
        {"q_num": 8, "type": "解答题", "topic_ids": ["series_power"], "keywords": ["幂级数"]},
    ],
    1997: [
        {"q_num": 1, "type": "选择题", "topic_ids": ["limit_inf_small"], "keywords": ["无穷小"]},
        {"q_num": 2, "type": "选择题", "topic_ids": ["continuity"], "keywords": ["连续"]},
        {"q_num": 3, "type": "选择题", "topic_ids": ["series_const"], "keywords": ["级数"]},
        {"q_num": 4, "type": "填空题", "topic_ids": ["limit_ops"], "keywords": ["极限"]},
        {"q_num": 5, "type": "填空题", "topic_ids": ["line_int2"], "keywords": ["曲线积分"]},
        {"q_num": 6, "type": "填空题", "topic_ids": ["det_compute"], "keywords": ["行列式"]},
        {"q_num": 7, "type": "解答题", "topic_ids": ["multi_chain"], "keywords": ["偏导数"]},
        {"q_num": 8, "type": "解答题", "topic_ids": ["double_int"], "keywords": ["二重积分"]},
        {"q_num": 9, "type": "解答题", "topic_ids": ["series_power"], "keywords": ["幂级数"]},
        {"q_num": 10, "type": "解答题", "topic_ids": ["eigen_similar"], "keywords": ["对角化"]},
    ],
    2004: [
        {"q_num": 1, "type": "选择题", "topic_ids": ["limit_important"], "keywords": ["重要极限", "无穷小"]},
        {"q_num": 2, "type": "选择题", "topic_ids": ["derivative_rules"], "keywords": ["隐函数求导"]},
        {"q_num": 3, "type": "选择题", "topic_ids": ["series_power"], "keywords": ["幂级数", "和函数"]},
        {"q_num": 4, "type": "选择题", "topic_ids": ["mvt_lagrange"], "keywords": ["中值定理", "极限"]},
        {"q_num": 5, "type": "选择题", "topic_ids": ["eigen_basic"], "keywords": ["特征值"]},
        {"q_num": 6, "type": "选择题", "topic_ids": ["linear_system"], "keywords": ["线性方程组"]},
        {"q_num": 7, "type": "选择题", "topic_ids": ["prob_classical"], "keywords": ["古典概型"]},
        {"q_num": 8, "type": "选择题", "topic_ids": ["rv_continuous"], "keywords": ["正态分布"]},
        {"q_num": 9, "type": "填空题", "topic_ids": ["defint_compute"], "keywords": ["定积分"]},
        {"q_num": 10, "type": "填空题", "topic_ids": ["ode_linear_high"], "keywords": ["微分方程", "特解"]},
        {"q_num": 11, "type": "填空题", "topic_ids": ["double_int"], "keywords": ["二重积分"]},
        {"q_num": 12, "type": "填空题", "topic_ids": ["line_int2"], "keywords": ["曲线积分"]},
        {"q_num": 13, "type": "填空题", "topic_ids": ["det_compute"], "keywords": ["行列式"]},
        {"q_num": 14, "type": "填空题", "topic_ids": ["rv_discrete"], "keywords": ["离散分布"]},
        {"q_num": 15, "type": "解答题", "topic_ids": ["limit_seq_criteria"], "keywords": ["数列极限", "单调"]},
        {"q_num": 16, "type": "解答题", "topic_ids": ["surface_int2"], "keywords": ["曲面积分"]},
        {"q_num": 17, "type": "解答题", "topic_ids": ["series_power"], "keywords": ["幂级数", "收敛域"]},
        {"q_num": 18, "type": "解答题", "topic_ids": ["multi_extrema"], "keywords": ["拉格朗日乘数法"]},
        {"q_num": 19, "type": "解答题", "topic_ids": ["eigen_similar"], "keywords": ["正交对角化"]},
        {"q_num": 20, "type": "解答题", "topic_ids": ["rv_function"], "keywords": ["随机变量函数"]},
        {"q_num": 21, "type": "解答题", "topic_ids": ["stat_estimation"], "keywords": ["参数估计"]},
    ],
    2010: [
        {"q_num": 1, "type": "选择题", "topic_ids": ["limit_inf_compare"], "keywords": ["无穷小比较"]},
        {"q_num": 2, "type": "选择题", "topic_ids": ["multi_chain"], "keywords": ["偏导数", "复合函数"]},
        {"q_num": 3, "type": "选择题", "topic_ids": ["improper"], "keywords": ["反常积分", "敛散性"]},
        {"q_num": 4, "type": "选择题", "topic_ids": ["derivative_app_monotonicity"], "keywords": ["单调性", "不等式"]},
        {"q_num": 5, "type": "选择题", "topic_ids": ["matrix_rank"], "keywords": ["矩阵秩", "可逆"]},
        {"q_num": 6, "type": "选择题", "topic_ids": ["eigen_basic"], "keywords": ["特征值", "特征向量"]},
        {"q_num": 7, "type": "选择题", "topic_ids": ["prob_classical"], "keywords": ["古典概型", "组合"]},
        {"q_num": 8, "type": "选择题", "topic_ids": ["stat_sample"], "keywords": ["统计量", "分布"]},
        {"q_num": 9, "type": "填空题", "topic_ids": ["defint_compute"], "keywords": ["定积分", "换元"]},
        {"q_num": 10, "type": "填空题", "topic_ids": ["line_int2"], "keywords": ["曲线积分", "格林公式"]},
        {"q_num": 11, "type": "填空题", "topic_ids": ["ode_linear_high"], "keywords": ["微分方程", "解结构"]},
        {"q_num": 12, "type": "填空题", "topic_ids": ["surface_int2"], "keywords": ["曲面积分"]},
        {"q_num": 13, "type": "填空题", "topic_ids": ["det_compute"], "keywords": ["行列式"]},
        {"q_num": 14, "type": "填空题", "topic_ids": ["rv_continuous"], "keywords": ["指数分布", "期望"]},
        {"q_num": 15, "type": "解答题", "topic_ids": ["taylor"], "keywords": ["泰勒公式", "极限"]},
        {"q_num": 16, "type": "解答题", "topic_ids": ["double_int"], "keywords": ["二重积分", "换元"]},
        {"q_num": 17, "type": "解答题", "topic_ids": ["series_power"], "keywords": ["幂级数", "和函数"]},
        {"q_num": 18, "type": "解答题", "topic_ids": ["triple_int"], "keywords": ["三重积分", "球坐标"]},
        {"q_num": 19, "type": "解答题", "topic_ids": ["eigen_similar"], "keywords": ["正交矩阵", "对角化"]},
        {"q_num": 20, "type": "解答题", "topic_ids": ["rv_function"], "keywords": ["随机变量函数分布"]},
        {"q_num": 21, "type": "解答题", "topic_ids": ["stat_estimation"], "keywords": ["矩估计", "最大似然"]},
    ],
    2017: [
        {"q_num": 1, "type": "选择题", "topic_ids": ["continuity"], "keywords": ["连续性", "参数"]},
        {"q_num": 2, "type": "选择题", "topic_ids": ["derivative_app_monotonicity"], "keywords": ["单调性", "不等式"]},
        {"q_num": 3, "type": "选择题", "topic_ids": ["directional_gradient"], "keywords": ["方向导数", "梯度"]},
        {"q_num": 4, "type": "选择题", "topic_ids": ["defint_physics"], "keywords": ["定积分应用", "路程"]},
        {"q_num": 5, "type": "选择题", "topic_ids": ["matrix_rank"], "keywords": ["秩", "特征值"]},
        {"q_num": 6, "type": "选择题", "topic_ids": ["eigen_similar"], "keywords": ["相似对角化"]},
        {"q_num": 7, "type": "选择题", "topic_ids": ["prob_cond"], "keywords": ["条件概率"]},
        {"q_num": 8, "type": "选择题", "topic_ids": ["stat_sample"], "keywords": ["抽样分布", "卡方"]},
        {"q_num": 9, "type": "填空题", "topic_ids": ["higher_deriv"], "keywords": ["高阶导数", "奇偶"]},
        {"q_num": 10, "type": "填空题", "topic_ids": ["ode_linear1"], "keywords": ["一阶线性", "微分方程"]},
        {"q_num": 11, "type": "填空题", "topic_ids": ["line_int2"], "keywords": ["曲线积分", "路径无关"]},
        {"q_num": 12, "type": "填空题", "topic_ids": ["series_power"], "keywords": ["幂级数", "和函数"]},
        {"q_num": 13, "type": "填空题", "topic_ids": ["vector_group"], "keywords": ["线性无关", "秩"]},
        {"q_num": 14, "type": "填空题", "topic_ids": ["expectation"], "keywords": ["期望", "混合分布"]},
        {"q_num": 15, "type": "解答题", "topic_ids": ["multi_chain"], "keywords": ["偏导数", "全微分"]},
        {"q_num": 16, "type": "解答题", "topic_ids": ["surface_int2"], "keywords": ["曲面积分", "高斯公式"]},
        {"q_num": 17, "type": "解答题", "topic_ids": ["series_power"], "keywords": ["幂级数", "收敛域"]},
        {"q_num": 18, "type": "解答题", "topic_ids": ["double_int"], "keywords": ["二重积分", "交换次序"]},
        {"q_num": 19, "type": "解答题", "topic_ids": ["triple_int"], "keywords": ["三重积分", "柱坐标"]},
        {"q_num": 20, "type": "解答题", "topic_ids": ["clt"], "keywords": ["中心极限定理"]},
        {"q_num": 21, "type": "解答题", "topic_ids": ["stat_estimation"], "keywords": ["矩估计", "最大似然"]},
    ],
}


class QuestionBank:
    """真题库管理器"""

    def __init__(self, knowledge_base=None):
        self.kb = knowledge_base
        self.index = EXAM_INDEX
        logger.info(f"📚 真题库就绪: {len(self.index)} 年真题索引")

    def get_years(self) -> List[int]:
        return sorted(self.index.keys(), reverse=True)

    def get_exam(self, year: int) -> List[Dict]:
        return self.index.get(year, [])

    def get_questions_by_topic(self, topic_id: str) -> List[Dict]:
        """获取某个知识点的所有真题"""
        results = []
        for year, questions in self.index.items():
            for q in questions:
                if topic_id in q.get('topic_ids', []):
                    results.append({"year": year, **q})
        return sorted(results, key=lambda x: x['year'], reverse=True)

    def get_hot_topics(self) -> List[Dict]:
        """获取高频考点统计"""
        topic_count = {}
        for year, questions in self.index.items():
            for q in questions:
                for tid in q.get('topic_ids', []):
                    topic_count[tid] = topic_count.get(tid, 0) + 1

        # 获取知识点名称
        results = []
        for tid, count in sorted(topic_count.items(), key=lambda x: -x[1]):
            name = tid
            chapter = ""
            if self.kb:
                match = self.kb.get_topic('math_one', tid)
                if match:
                    name = match['topic'].get('name', tid)
                    chapter = match.get('chapter', '')
            results.append({'topic_id': tid, 'name': name, 'chapter': chapter, 'frequency': count})
        return results

    def build_exam_context(self, topic_id: str, limit: int = 5) -> str:
        """构建给 AI 的真题上下文"""
        questions = self.get_questions_by_topic(topic_id)
        if not questions:
            return "暂无相关真题数据"

        lines = [f"该知识点历年真题({len(questions)}道):"]
        for q in questions[:limit]:
            lines.append(f"  {q['year']}年 第{q['q_num']}题 ({q['type']}) — {', '.join(q['keywords'])}")

        # 添加考频趋势
        recent = [q for q in questions if q['year'] >= 2020]
        if recent:
            lines.append(f"\n近5年出现{len(recent)}次" + ("(高频!)" if len(recent) >= 3 else ""))

        return '\n'.join(lines)
